<?php

namespace App\Modules\AI\Domain\ValueObjects;

/**
 * MatchScoreResult — the single source of truth for the "Investor-Project
 * Matching" capability's output shape, mirroring `AiPrecheckResult`'s
 * centralized-serialization pattern (one `toApiPayload()`, never a
 * hand-rolled array in a Controller).
 *
 * CRITICAL, deliberate departure from `AiPrecheckResult`/`AiDocumentVerificationResult`:
 * this VO has NO `recommendation` field and its `toApiPayload()` label is
 * "Profile Compatibility Score", never "AI Recommendation". PDL-002
 * ("AI is analytical only... never issues recommendations or verdicts") is
 * the platform's SECOND foundational rule — PDL-053/PDL-058's "AI
 * Recommendation" labeling exists only for the narrow Compliance
 * pre-check carve-out; it must never be reused here. New PDL-061 (added
 * this Sprint) formalizes that this capability's output is limited to
 * describing PREFERENCE-ATTRIBUTE alignment (industry, risk band, prior
 * engagement) and must never contain investment-merit judgment or a
 * suggestion to invest/not invest. `reasons` below are rule-based, templated
 * strings generated by `MatchScoringCalculator` — never free-form
 * AI-generated text — precisely so this guarantee can be verified by
 * reading the calculator's source, not merely trusted from a prompt.
 */
final class MatchScoreResult
{
    private function __construct(
        public readonly bool $available,
        public readonly ?string $unavailableReason,
        public readonly string $investorProfileId,
        public readonly string $projectId,
        public readonly ?int $score,
        public readonly ?MatchTier $tier,
        public readonly array $breakdown,
        public readonly array $reasons,
        public readonly ?float $confidence,
    ) {
    }

    public static function unavailable(string $investorProfileId, string $projectId, string $reason): self
    {
        return new self(
            available: false,
            unavailableReason: $reason,
            investorProfileId: $investorProfileId,
            projectId: $projectId,
            score: null,
            tier: null,
            breakdown: [],
            reasons: [],
            confidence: null,
        );
    }

    /**
     * @param  array<string, int>  $breakdown  per-criterion score, 0-100 each
     * @param  array<int, string>  $reasons  templated, rule-based explanation strings
     */
    public static function fromComputed(
        string $investorProfileId,
        string $projectId,
        int $score,
        array $breakdown,
        array $reasons,
        float $confidence,
    ): self {
        return new self(
            available: true,
            unavailableReason: null,
            investorProfileId: $investorProfileId,
            projectId: $projectId,
            score: $score,
            tier: MatchTier::fromScore($score),
            breakdown: $breakdown,
            reasons: $reasons,
            confidence: $confidence,
        );
    }

    public static function fromPersisted(
        string $investorProfileId,
        string $projectId,
        int $score,
        array $breakdown,
        array $reasons,
        ?float $confidence,
    ): self {
        return new self(
            available: true,
            unavailableReason: null,
            investorProfileId: $investorProfileId,
            projectId: $projectId,
            score: $score,
            tier: MatchTier::fromScore($score),
            breakdown: $breakdown,
            reasons: $reasons,
            confidence: $confidence,
        );
    }

    /**
     * Locked response contract for proposed API-032. Deliberately titled
     * "Profile Compatibility Score" — see this class's doc comment for why
     * "AI Recommendation" (PDL-058's label, Compliance-only) must never
     * appear here.
     */
    public function toApiPayload(): array
    {
        return [
            'label' => 'Profile Compatibility Score', // NOT "AI Recommendation" — see PDL-061
            'available' => $this->available,
            'unavailable_reason' => $this->unavailableReason,
            'investor_profile_id' => $this->investorProfileId,
            'project_id' => $this->projectId,
            'score' => $this->score,
            'tier' => $this->tier?->value,
            'breakdown' => $this->breakdown,
            'reasons' => $this->reasons,
            'confidence' => $this->confidence,
            'disclaimer' => 'This score describes how closely the investor\'s stated preferences '
                . '(industry, risk appetite, prior engagement) align with the project\'s stated '
                . 'attributes. It is NOT investment advice, a deal-quality assessment, or a '
                . 'suggestion to invest (PDL-002, PDL-061). The Investor makes their own decision.',
        ];
    }
}
